#!/bin/bash


lftp -e "mirror --delete --parallel=4 /centos/8/BaseOS/x86_64/ /var/www/html/centos/8/BaseOS/x86_64/; bye" https://mirrors.kernel.org
lftp -e "mirror --delete --parallel=4 /centos/8/AppStream/x86_64/ /var/www/html/centos/8/AppStream/x86_64/; bye" https://mirrors.kernel.org
lftp -e "mirror --delete --parallel=4 /centos/8/extras/x86_64/ /var/www/html/centos/8/extras/x86_64/; bye" https://mirrors.kernel.org
