#!/bin/bash

# Shimcopy
cp /boot/efi/EFI/centos/shimx64.efi /var/lib/tftpboot/shim.efi
cp /boot/efi/EFI/centos/shimx64-centos.efi /var/lib/tftpboot/

# Copy all other needfull stuff...
cp /tftpboot/vesamenu.c32 /var/lib/tftpboot/
cp /tftpboot/pxelinux.0 /var/lib/tftpboot/
cp /tftpboot/libutil.c32 /var/lib/tftpboot/
cp /tftpboot/libcom32.c32 /var/lib/tftpboot/
cp /tftpboot/ldlinux.c32 /var/lib/tftpboot/


releasever=8
#yum -y install wget
#wget http://mirror.centos.org/centos-$releasever/$releasever/os/x86_64/images/pxeboot/vmlinuz -O /var/lib/tftpboot/vmlinuz
#wget http://mirror.centos.org/centos-$releasever/$releasever/os/x86_64/images/pxeboot/initrd.img -O /var/lib/tftpboot/initrd.img
mkdir -p /var/lib/tftpboot/centos/8/BaseOS/x86_64/kickstart/images/pxeboot/
wget http://mirror.centos.org/centos-8/8/BaseOS/x86_64/kickstart/images/pxeboot/vmlinuz \
 -O /var/lib/tftpboot/centos/8/BaseOS/x86_64/kickstart/images/pxeboot/vmlinuz
wget http://mirror.centos.org/centos/8/BaseOS/x86_64/kickstart/images/pxeboot/initrd.img \
 -O /var/lib/tftpboot/centos/8/BaseOS/x86_64/kickstart/images/pxeboot/initrd.img

# Enable and start
systemctl enable dhcpd.service
systemctl start dhcpd.service

# Enable DNS
systemctl enable dnsmasq.service
systemctl start dnsmasq.service
firewall-cmd --permanent --add-service=dns

# Enable NTP server
firewall-cmd --permanent --add-service=ntp
sed -i 's|#allow 192.168.0.0/16|allow 10.98.20.0/24|' /etc/chrony.conf

