#!/bin/bash

#mkdir -p /var/www/html/centos/7

#rsync -avzH --delete rsync://rsync.kernel.org/centos/7/os /var/www/html/centos/7/
#rsync -aqzH --delete rsync://rsync.kernel.org/centos/7/updates /var/www/html/centos/7/
#rsync -aqzH --delete rsync://rsync.kernel.org/centos/7/extras /var/www/html/centos/7/

#lftp -e "mirror --parallel=4 /centos/7/os/x86_64/ /var/www/html/centos/7/os/x86_64/; bye" ftp://mirrors.kernel.org
#lftp -e "mirror --parallel=4 /centos/7/updates/x86_64/ /var/www/html/centos/7/updates/x86_64/; bye" ftp://mirrors.kernel.org
#lftp -e "mirror --parallel=4 /centos/7/extras/x86_64/ /var/www/html/centos/7/extras/x86_64/; bye" ftp://mirrors.kernel.org
#lftp -e "mirror --parallel=4 /fedora/releases/24/Everything/x86_64/os/images/pxeboot/ /var/www/html/pub/fedora/linux/releases/24/Everything/x86_64/os/images/pxeboot/" ftp://mirrors.kernel.org

#lftp -e "mirror --delete --parallel=4 /centos/7/os/x86_64/ /var/www/html/centos/7/os/x86_64/; bye" https://mirrors.kernel.org
#lftp -e "mirror --delete --parallel=4 /centos/7/updates/x86_64/ /var/www/html/centos/7/updates/x86_64/; bye" https://mirrors.kernel.org
#lftp -e "mirror --delete --parallel=4 /centos/7/extras/x86_64/ /var/www/html/centos/7/extras/x86_64/; bye" https://mirrors.kernel.org

lftp -e "mirror --delete --parallel=4 /centos-8/8/BaseOS/x86_64/ /var/www/html/centos-8/8/BaseOS/x86_64/; bye" https://mirrors.kernel.org
lftp -e "mirror --delete --parallel=4 /centos-8/8/AppStream/x86_64/ /var/www/html/centos-8/8/AppStream/x86_64/; bye" https://mirrors.kernel.org
lftp -e "mirror --delete --parallel=4 /centos-8/8/extras/x86_64/ /var/www/html/centos-8/8/extras/x86_64/; bye" https://mirrors.kernel.org
